# Generated by Django 4.2.8 on 2026-01-22 17:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("current_stock", models.PositiveIntegerField(default=0)),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Days between order placement and receipt"
                    ),
                ),
                (
                    "reorder_point",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum stock level to trigger reorder"
                    ),
                ),
                (
                    "safety_stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer stock for demand variability"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("linear_regression", "Linear Regression"),
                            ("random_forest", "Random Forest"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mae", models.FloatField()),
                ("rmse", models.FloatField()),
                ("r2_score", models.FloatField()),
                (
                    "train_test_split",
                    models.FloatField(
                        default=0.8,
                        help_text="Proportion used for training (e.g., 0.8 = 80/20)",
                    ),
                ),
                ("training_samples", models.PositiveIntegerField()),
                ("test_samples", models.PositiveIntegerField()),
                ("evaluation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about evaluation"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_evaluations",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("understock", "Understock Risk"),
                            ("overstock", "Overstock Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Natural language explanation of the risk"
                    ),
                ),
                (
                    "forecasted_demand_7d",
                    models.FloatField(help_text="7-day forecasted demand"),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(
                        help_text="Stock level when alert generated"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_level", "-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                (
                    "predicted_demand",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        choices=[
                            ("linear_regression", "Linear Regression"),
                            ("random_forest", "Random Forest"),
                            ("ensemble", "Ensemble"),
                        ],
                        default="random_forest",
                        max_length=20,
                    ),
                ),
                (
                    "mae",
                    models.FloatField(
                        blank=True,
                        help_text="Mean Absolute Error for model evaluation",
                        null=True,
                    ),
                ),
                (
                    "rmse",
                    models.FloatField(
                        blank=True,
                        help_text="Root Mean Squared Error for model evaluation",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-forecast_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_sold",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("sale_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_records",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "sale_date"],
                        name="inventory_s_product_6b33d6_idx",
                    ),
                    models.Index(
                        fields=["sale_date"], name="inventory_s_sale_da_4b7d68_idx"
                    ),
                ],
                "unique_together": {("product", "sale_date")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["owner", "-updated_at"], name="inventory_p_owner_i_15c8c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["current_stock"], name="inventory_p_current_d3d6aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelevaluation",
            index=models.Index(
                fields=["product", "model_name"], name="inventory_m_product_0c89c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(
                fields=["product", "-generated_at"],
                name="inventory_i_product_0adce3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(
                fields=["alert_type", "risk_level"],
                name="inventory_i_alert_t_68c847_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="demandforecast",
            index=models.Index(
                fields=["product", "forecast_date"],
                name="inventory_d_product_7a8eb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="demandforecast",
            index=models.Index(
                fields=["forecast_date"], name="inventory_d_forecas_5cb63a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="demandforecast",
            unique_together={("product", "forecast_date", "model_used")},
        ),
    ]
